# Cấu hình docker-compose cho 3 services: wordpress, db, nginx
# Sử dụng phiên bản mới nhất của wordpress, mysql, nginx từ Docker Hub
# Mount thư mục hiện tại vào các thư mục của container
# Mở cổng 8080 của máy host và map vào cổng 80 của container wordpress
# Mở cổng 80 của máy host và map vào cổng 80 của container nginx

# Sử dụng phiên bản mới nhất của docker-compose
version: '3'

# Danh sách tất cả services (containers) cần chạy
# bao gồm wordpress, db, nginx
services:
  # Service đầu tiên (wordpress)
  wordpress:
    # Sử dụng phiên bản mới nhất của wordpress từ Docker Hub
    # Docker Hub wordpress: https://hub.docker.com/_/wordpress
    image: wordpress:latest
    # Luôn khởi động lại container nếu container bị dừng
    restart: always
    # Mở cổng 8080 của máy host và map vào cổng 80 của container
    ports:
      - "8080:80"
    # Cấu hình biến môi trường cho wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    # Mount thư mục hiện tại vào thư mục /var/www/html của container
    volumes:
    # - ./wordpress:/var/lib/mysql
      - wordpress:/var/www/html

  # Service thứ hai (db)
  db:
    # Sử dụng phiên bản mới nhất của mysql từ Docker Hub
    # Docker Hub mysql: https://hub.docker.com/_/mysql
    image: mysql:latest
    # Luôn khởi động lại container nếu container bị dừng
    restart: always
    # Cấu hình biến môi trường cho mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    # Mount thư mục hiện tại vào thư mục /var/lib/mysql của container
    volumes:
    # - ./mysql:/var/lib/mysql
      - mysql:/var/lib/mysql

  # Service thứ ba (nginx)
  nginx:
    # Sử dụng phiên bản mới nhất của nginx từ Docker Hub
    # Docker Hub nginx: https://hub.docker.com/_/nginx
    image: nginx:latest
    # Luôn khởi động lại container nếu container bị dừng
    restart: always
    # Mở cổng 80 của máy host và map vào cổng 80 của container
    ports:
      - "80:80"
    # Mount thư mục hiện tại vào thư mục /etc/nginx/conf.d của container
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - wordpress:/var/www/html

volumes:
  mysql: 
  wordpress:
