# File của Github Actions

name: CI/CD Pipeline

# Chạy khi có sự kiện push hoặc pull request trên nhánh main hoặc CICD_Test
on:
  push:
    branches: [ main, CICD_Test ]
  pull_request:
    branches: [ main, CICD_Test ]

# Các công việc cần thực hiện
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # build job sẽ chạy trên container của mysql:5.7
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3

    - name: Validate Composer files
      uses: docker://composer:1.9.0
      with:
        args: validate

    - name: Install Dependencies
      uses: docker://composer:1.9.0
      with:
        args: install

    - name: Run Tests
      run: |
        docker-compose up -d
