name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3

    - name: Validate Composer files
      uses: docker://composer:1.9.0
      with:
        args: validate

    - name: Install Dependencies
      uses: docker://composer:1.9.0
      with:
        args: install

    - name: Run Tests
      run: |
        docker-compose up -d
