name: CI/CD Pipeline

on:
  push:
    branches: [ CICD_Test ]
  pull_request:
    branches: [ CICD_Test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate Composer files
      uses: docker://composer:1.9.0
      with:
        args: validate

    - name: Install Dependencies
      uses: docker://composer:1.9.0
      with:
        args: install

    - name: Run Tests
      run: |
        docker-compose up